#!/usr/bin/env bash
# This script is for install a Nginx server:

sudo apt-get update
sudo apt-get install nginx -y
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sudo ufw allow 'Nginx FULL'
