#!/usr/bin/env bash
# This script is for install a Nginx server:

sudo apt-get update
sudo apt-get install nginx -y
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo systemctl restart nginx.service
