#!/usr/bin/env bash
# This script is for install a Nginx server:

sudo apt-get update
sudo apt-get install nginx -y
sudo chgrp www-data /var/www/html
sudo chmod -R 775 /var/www/html
sudo chmod -R g+s /var/www/html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start
