#!/usr/bin/env bash
#Custom 404 error page

sudo apt-get update
sudo apt-get install nginx -y
sudo chgrp www-data /var/www/html
sudo chmod -R 775 /var/www/html
sudo chmod -R g+s /var/www/html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx start

sudo chmod -R 777 /etc/nginx
sudo chmod -R g+s /etc/nginx
sed -i '18 a \ \n\t rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sudo service nginx restart

echo "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/custom_404.html
sed -i '35 a \ \t error_page 404 /custom_404.html; \n\t location = /custom_404.html { \n\t\t root /usr/share/nginx/html; \n\t\t internal; \n\t}' /etc/nginx/sites-available/default
sudo service nginx restart
