#!/usr/bin/env bash
# Add a custom HTTP header in NGINX.CONF
sudo apt-get update
sudo apt-get install nginx -y

echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i '18 a \ \n\t rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/page_404.html
sudo sed -i '35 a \ \n\t error_page 404 /page_404.html; \n\t location = /page_404.html { \n\t\t root /usr/share/nginx/html; \n\t\t internal; \n\t}' /etc/nginx/sites-enabled/default

sudo sed -i "/http {/a \ \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

sudo service nginx restart
