#!/usr/bin/env bash
# Config a HAproxy in a load balancer server:
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y

sudo apt-get update -y
sudo apt-get install haproxy -y

sudo chmod 777 /etc/haproxy/
sudo chmod 777 /etc/haproxy/haproxy.cfg
sudo sed -i "$ a frontend Local_Server \n\t bind *:80 \n\t mode http \n\t default_backend My_Web_Servers \n\n backend My_Web_Servers \n\t mode http \n\t balance roundrobin \n\t server 1150-web-01 104.196.21.123:80 check \n\t server 1150-web-02 54.226.145.255:80 check \n" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
