#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it.

# Create the file name with DATE data
foldername=$(date +%d-%m-%Y)
# Create the backup
mysqldump -u root -p"$1" --all-databases > backup.sql
# Compress the file
tar -cvzf "$foldername".tar.gz backup.sql
