#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times with WHILE loop.
#+ and have a condition.
count=0
while [ $count -lt 10 ]
do
    if [ $count -eq 9 ]
    then
        echo "Hi"
    fi
    echo "Holberton School"
    let count+=1
done
