#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times with WHILE loop.
#+ but change in the 4th, 9th and 17th iteration.
count=0
while [[ $count -lt 20 ]]
do
    case $count in
        4)
            echo "bad luck from China" ;;
        9)
            echo "bad luck from Japan" ;;
        17)
            echo "bad luck from Italy" ;;
    esac
    let count+=1
    echo "$count"
done
