#!/usr/bin/env bash
# This script is displaying "A clock" with WHILE loop.
hour=0
minutes=1
while [[ $hour -lt 13 ]]
do
    echo "Hour: $hour"
    while [[ $minutes -lt 60 ]]
    do
        echo "$minutes"
        let minutes+=1
    done
    minutes=0
    let hour+=1
done
