#!/usr/bin/env bash
#localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8

cp /etc/hosts /etc/hosts.new
echo "127.0.0.2 localhost" > /etc/hosts.new
echo "8.8.8.8 www.facebook.com facebook.com" >> /etc/hosts.new
cp -f /etc/hosts.new /etc/hosts
